/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author laptop
 */
public class ViewLogin extends javax.swing.JFrame {

    /**
     * Creates new form ViewLogin
     */
    public ViewLogin() {
        initComponents();
        this.setTitle("Quản Lý Sinh Viên - Đăng nhập");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        txtPassWord = new javax.swing.JPasswordField();
        btnlogin = new javax.swing.JButton();
        chkRemenber = new javax.swing.JCheckBox();
        anh = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Tên đăng nhập : ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(6, 108, 114, 20);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Mật khẩu : ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(6, 148, 110, 20);

        txtUserName.setForeground(new java.awt.Color(153, 153, 153));
        txtUserName.setText("admin");
        txtUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserNameActionPerformed(evt);
            }
        });
        txtUserName.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtUserNamePropertyChange(evt);
            }
        });
        getContentPane().add(txtUserName);
        txtUserName.setBounds(130, 110, 170, 19);

        txtPassWord.setForeground(new java.awt.Color(153, 153, 153));
        txtPassWord.setText("12345");
        txtPassWord.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtPassWordPropertyChange(evt);
            }
        });
        getContentPane().add(txtPassWord);
        txtPassWord.setBounds(130, 150, 170, 19);

        btnlogin.setBackground(new java.awt.Color(255, 102, 0));
        btnlogin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnlogin.setForeground(new java.awt.Color(255, 255, 255));
        btnlogin.setText("Đăng Nhập ");
        btnlogin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
            }
        });
        getContentPane().add(btnlogin);
        btnlogin.setBounds(120, 210, 90, 30);

        chkRemenber.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        chkRemenber.setForeground(new java.awt.Color(255, 102, 0));
        chkRemenber.setText("Ghi Nhớ ? ");
        getContentPane().add(chkRemenber);
        chkRemenber.setBounds(161, 182, 87, 23);

        anh.setForeground(new java.awt.Color(153, 153, 153));
        anh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/util/image/aaaa.png"))); // NOI18N
        getContentPane().add(anh);
        anh.setBounds(0, 5, 500, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
        // TODO add your handling code here:
        if (txtUserName.getText().equals("admin") && txtPassWord.getText().equals("12345")) {
            this.dispose();
            ViewHome home = new ViewHome();
            home.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(this, "Tài khoản hoặc mật khẩu không chính xác");
        }
    }//GEN-LAST:event_btnloginActionPerformed

    private void txtUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserNameActionPerformed

    private void txtUserNamePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtUserNamePropertyChange
        // TODO add your handling code here:
        txtUserName.setForeground(Color.black);
    }//GEN-LAST:event_txtUserNamePropertyChange

    private void txtPassWordPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtPassWordPropertyChange
        // TODO add your handling code here:
        txtPassWord.setForeground(Color.black);
    }//GEN-LAST:event_txtPassWordPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel anh;
    private javax.swing.JButton btnlogin;
    private javax.swing.JCheckBox chkRemenber;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField txtPassWord;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
